plugins {
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

version = '0.0.2'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    implementation 'com.github.oshi:oshi-core:6.6.5'
    implementation 'com.formdev:flatlaf:3.7'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.11.3'
}

application {
    mainClass = 'ru.mcs.sysmon.cli.Main'
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('sysmon')
    archiveClassifier.set('')
    manifest {
        attributes 'Implementation-Version': project.version
    }
}

wrapper {
    gradleVersion = '8.11.1'
    distributionType = Wrapper.DistributionType.BIN
}
